# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPelicula', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[(b'Comedia', b'Comedia'), (b'Romance', b'Romance'), (b'Suspenso', b'Suspenso'), (b'Drama', b'Drama'), (b'Accion', b'Accion'), (b'Terror', b'Terror')], max_length=20)),
                ('clasificacion', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('interpretes', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('imagenPortada', models.FileField(upload_to=b'/static/imagenes/')),
                ('nacionalidad', models.CharField(max_length=20)),
                ('anio', models.DateField()),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSala', models.CharField(max_length=20)),
                ('NumSala', models.IntegerField()),
                ('NumAsientos', models.IntegerField()),
                ('TipoDeSala', models.CharField(choices=[(b'Sala3d', b'Sala3d'), (b'SalaHD', b'SalaHD'), (b'SalaNormal', b'SalaNormal')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalaSesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSalaSesion', models.CharField(max_length=20)),
                ('id_Sala', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='appCinemax.Sala')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSesion', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('PrecioPorAsiento', models.FloatField()),
                ('AsientosLibres', models.IntegerField()),
                ('AsientosVendidos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='salasesion',
            name='id_Sesion',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='appCinemax.Sesion'),
        ),
    ]
