# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCinemax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagenPortada',
            field=models.FileField(blank=True, null=True, upload_to=b'/static/imagenes/'),
        ),
    ]
