# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCinemax', '0010_auto_20160823_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='id',
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='idSesion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
