# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCinemax', '0011_auto_20160823_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salasesion',
            name='id',
        ),
        migrations.AlterField(
            model_name='salasesion',
            name='idSalaSesion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
