# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appCinemax', '0012_auto_20160823_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='NumSesion',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sala',
            name='NumSala',
            field=models.CharField(max_length=5),
        ),
    ]
