# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCinemax', '0013_auto_20160823_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(choices=[(b'A', b'A'), (b'B', b'B'), (b'C', b'C'), (b'E', b'E')], max_length=30),
        ),
    ]
