# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCinemax', '0014_auto_20160823_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='anio',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idPelicula',
            field=models.CharField(max_length=5),
        ),
    ]
