# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appCinemax', '0016_auto_20160824_0621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='nacionalidad',
        ),
    ]
